### ISSUE TITLE
Failed to resolve entry for package "crypto"

### ISSUE THREAD

**Issue by g1ronn1mo** [fathelen/crypt4ghJS#3]
When trying to import the module with:

`import crypt4gh from 'crypt4gh_js';`

I got the Error:

Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its package.json.

Full Stack:

```
ERROR  error while updating dependencies:                                                                                                 12:10:26 PM
Error: Build failed with 1 error:
node_modules/esbuild/lib/main.js:1374:21: ERROR: [plugin: vite:dep-pre-bundle] Failed to resolve entry for package "crypto". The package may have incorrect main/module/exports specified in its package.json.
    at failureErrorWithLog (/home/bschwab/projects/openbis-nuxt-plugin-dev/packages/openbis-layer/node_modules/esbuild/lib/main.js:1651:15)
    at /home/bschwab/projects/openbis-nuxt-plugin-dev/packages/openbis-layer/node_modules/esbuild/lib/main.js:1059:25
    at /home/bschwab/projects/openbis-nuxt-plugin-dev/packages/openbis-layer/node_modules/esbuild/lib/main.js:1527:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by g1ronn1mo** [comment]
Similar Error here: 

https://stackoverflow.com/questions/54162297/module-not-found-error-cant-resolve-crypto

My guess to resolve is to use [crypto-browserify](https://www.npmjs.com/package/crypto-browserify). The goal of this module is to reimplement node's crypto module, in pure javascript so that it can run in the browser.

**Comment by fathelen** [comment]
removed crypto package
